spring.application.name=pay_my_buddy

spring.h2.console.enabled=true

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

logging.level.org.springframework.security=DEBUG