spring.application.name=pay_my_buddy

spring.h2.console.enabled=true

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.datasource.url = ${PAY_MY_BUDDY_DB_URL}
spring.datasource.username = ${PAY_MY_BUDDY_DB_USERNAME}
spring.datasource.password = ${PAY_MY_BUDDY_DB_PASSWORD}

logging.level.org.springframework.security=DEBUG